- name: Run experiments
  block:
    - name: Check workload is supported
      stat:
        path: "{{ playbook_dir }}/tasks/stress-tests/workloads/{{ run_workload_file }}"
      register: supported_workload

    - name: Show workload not supported error
      fail:
        msg: "Workload {{ workload }} is not supported"
      when: not supported_workload.stat.exists

    - name: Show distribution
      debug:
        msg: "Distribution is {{ dist_name }}: {{ distribution }}"

    - name: Remove timestamps file if already exists
      file:
        path: "{{ timestamps_file }}"
        state: absent

    - name: Run workload sequential experiments
      include_tasks: workloads/{{ run_workload_file }}
      loop: "{{ range(10, 101, 10) | list }}"
      loop_control:
        loop_var: seq_load
      when: supported_workload.stat.exists
      vars:
        last_position: "1"
        load: "{{ seq_load | int }}"

    - name: Run workload adding cores incrementally
      include_tasks: workloads/{{ run_workload_file }}
      loop: "{{ range(0, distribution | length + 1, 2) | list }}"
      loop_control:
        loop_var: distribution_iter
      when: supported_workload.stat.exists
      vars:
        last_position: "{{ distribution_iter | int + 2 }}"
        load: "{{ (distribution_iter | int // 2 + 1) * 200 }}"

    - name: get the username running the deploy
      become: no
      local_action: command whoami
      register: username_on_the_host

    - name: Copy timestamps file to project timestamps directory
      copy:
        src: "{{ timestamps_file }}"
        dest: "{{ project_timestamps_file }}"
        owner: "{{ username_on_the_host.stdout_lines[0] }}"

  vars:
    - run_workload_file: "run_{{ workload }}.yml"
    - experiment_duration: 180
