- name: Check for previous apptainer installation
  shell: "which {{ singularity_command_alias }}"
  register: result
  ignore_errors: true

- name: Show apptainer not installed error message
  fail:
    msg: "Container engine '{{ container_engine }}' is not installed. Please install it before running this playbook."
  when: result is failed