- name: Start HWPC Sensor inside an apptainer/singularity container
  block:
    - name: Copy HWPC Sensor container definition file
      template:
        src: "templates/hwpc-sensor/{{ definition_file }}"
        dest: "{{ hwpc_sensor_path }}/image/{{ definition_file }}"

    - name: Copy HWPC Sensor configuration files
      template:
        src: "templates/hwpc-sensor/config/{{ item }}"
        dest: "{{ hwpc_sensor_path }}/config/{{ item }}"
      with_items:
        - hwpc-sensor-config.json
        - hwpc-sensor-entrypoint.sh

    - name: Build image
      shell: "{{ singularity_command_alias }} build image/{{ image_file }} image/{{ definition_file }}"
      args:
        chdir: "{{ hwpc_sensor_path }}"
        executable: /bin/bash
        creates: "image/{{ image_file }}"

    - name: Check containers status
      shell: "sudo {{ singularity_command_alias }} instance list -j"
      register: apptainer_list_output
      args:
        executable: /bin/bash

    - name: Wait for MongoDB to be up before starting HWPC Sensor
      wait_for:
        host: "{{ mongodb_host }}"
        port: "{{ mongodb_port }}"
        state: started
        delay: 5
        timeout: 300
    
    - name: Get last available core
      shell: "python3 -c 'import multiprocessing;  print(multiprocessing.cpu_count()-1)'"
      register: last_core

    - name: Start HWPC Sensor apptainer container on last available core
      shell: "sudo {{ singularity_command_alias }} instance start -C --net --cpus 0.5 --cpuset-cpus {{ last_core.stdout }} --bind /sys:/sys --bind {{ hwpc_sensor_reporting_path }}:/reporting image/{{ image_file }} {{ container_name }}"
      when: "'\"instance\": \"{{ container_name }}\",' not in apptainer_list_output.stdout"
      args:
        chdir: "{{ hwpc_sensor_path }}"
        executable: /bin/bash
  when: "container_engine == 'apptainer'"
  vars:
    - definition_file: "hwpc-sensor.def"
    - image_file: "hwpc-sensor.sif"
    - container_name: "hwpc-sensor"

- name: Start HWPC Sensor inside a docker container
  debug:
    msg: 'HWPC Sensor inside a docker container not yet supported'
  when: "container_engine == 'docker'"