- name: Install senders requirements
  shell: "python3 -m pip install -r scripts/senders/requirements.txt"
  when: "'power_sender' not in tmux_output.stdout"
  args:
    executable: /bin/bash

- name: Tmux session check
  shell: tmux ls
  register: tmux_output
  ignore_errors: yes

- name: Start tmux session for Power Sender
  shell: "bash scripts/senders/start_power_sender_tmux.sh"
  when: "'power_sender' not in tmux_output.stdout"
  args:
    executable: /bin/bash