- name: Start SmartWatts inside an apptainer/singularity container
  block:
    - name: Copy SmartWatts container definition file
      template:
        src: "templates/smartwatts/{{ definition_file }}"
        dest: "{{ smartwatts_path }}/image/{{ definition_file }}"

    - name: Copy SmartWatts configuration files
      template:
        src: "templates/smartwatts/config/{{ item }}"
        dest: "{{ smartwatts_path }}/config/{{ item }}"
      with_items:
        - smartwatts-config.json

    - name: Build image
      shell: "{{ singularity_command_alias }} build image/{{ image_file }} image/{{ definition_file }}"
      args:
        chdir: "{{ smartwatts_path }}"
        executable: /bin/bash
        creates: "image/{{ image_file }}"

    - name: Check containers status
      shell: "sudo {{ singularity_command_alias }} instance list -j"
      register: apptainer_list_output
      args:
        executable: /bin/bash

    - name: Wait for MongoDB to be up before starting SmartWatts
      wait_for:
        host: "{{ mongodb_host }}"
        port: "{{ mongodb_port }}"
        state: started
        delay: 5
        timeout: 300

    - name: Start SmartWatts apptainer container
      shell: "sudo {{ singularity_command_alias }} instance start -C --bind {{ smartwatts_output }}:/sensor-output image/{{ image_file }} {{ container_name }}"
      when: "'\"instance\": \"{{ container_name }}\",' not in apptainer_list_output.stdout"
      args:
        chdir: "{{ smartwatts_path }}"
        executable: /bin/bash
  when: "container_engine == 'apptainer'"
  vars:
    - smartwatts_output: "{{ smartwatts_path }}/output"
    - definition_file: "smartwatts.def"
    - image_file: "smartwatts.sif"
    - container_name: "smartwatts"

- name: Start SmartWatts inside a docker container
  debug:
    msg: 'SmartWatts inside a docker container not yet supported'
  when: "container_engine == 'docker'"