- name: Copy stress tests directory
  copy:
    src: scripts/stress-tests/
    dest: "{{ stress_tests_path }}"
    recursive: yes

- name: Copy stress tests environment variables
  template:
    src: "templates/stress-tests/get-env.sh"
    dest: "{{ stress_tests_path }}/bin/get-env.sh"