- name: Install senders requirements
  shell: "python3 -m pip install -r {{ senders_path }}/requirements.txt"
  args:
    executable: /bin/bash

- name: Tmux session check
  shell: tmux ls
  register: tmux_output
  ignore_errors: yes

- name: Start tmux session for Usage Sender
  shell: "bash {{ senders_path }}/start_usage_sender_tmux.sh"
  when: "'usage_sender' not in tmux_output.stdout"
  args:
    executable: /bin/bash